apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "redhat.com/v1beta1",
          "kind": "FruitsCatalogA1",
          "metadata": {
            "name": "example-fruitscataloga"
          },
          "spec": {
            "name": "fruits-catalog-ansible",
            "webapp": {
              "replicaCount": 2
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: fruits-catalog-ansible-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: FruitsCatalogA1
      name: fruitscataloga1s.redhat.com
      version: v1beta1
      resources:
        - kind: Secret
          name: ''
          version: v1
        - kind: Service
          name: ''
          version: v1
        - kind: Deployment
          name: ''
          version: v1 
        - kind: PersistentVolumeClaim
          name: ''
          version: v1
      specDescriptors:
        - description: Name of your FruitsCatalog
          displayName: Name
          path: name
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:label'
      statusDescriptors:
        - description: Name of your FruitsCatalog
          displayName: Name
          path: name
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:label'
  description: Operator for the FruitsCatalog app using Operator Ansible SDK 1.0.0
  displayName: fruits-catalog-ansible-operator-1.0.0
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - redhat.com
          resources:
          - fruitscataloga1s
          - fruitscataloga1s/status
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - redhat.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: fruits-catalog-ans-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --leader-election-id=fruits-catalog-ansible-operator
                image: quay.io/lbroudoux/fruits-catalog-ansible-operator:0.0.2
                name: manager
                resources: {}
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sample
  - operator-sdk
  - fruits-catalog
  links:
  - name: Fruits Catalog Ansible Operator
    url: https://fruits-catalog-ansible-operator.domain
  maintainers:
  - email: laurent.broudoux@redhat.com
    name: lbroudoux
  maturity: alpha
  provider:
    name: Laurent Broudoux
    url: https://github.com/redhat-france-sa/openshift-by-example-operators
  version: 0.0.1
