apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruits-catalog-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fruits-catalog-helm-operator
  template:
    metadata:
      labels:
        name: fruits-catalog-helm-operator
    spec:
      serviceAccountName: fruits-catalog-helm-operator
      containers:
        - name: fruits-catalog-helm-operator
          # Replace this with the built image name
          image: quay.io/lbroudoux/fruits-catalog-helm-operator:0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "fruits-catalog-helm-operator"
