---
# tasks file for fruitscataloga1

- name: Load default values from defaults/main.yml
  include_vars:
    file: ../defaults/main.yml
    name: default_cr

- name: Complete CR with default values
  set_fact:
    webapp_full: "{{ default_cr.webapp|combine(webapp, recursive=True) }}"
    mongodb_full: "{{ default_cr.mongodb|combine(mongodb, recursive=True) }}"

- name: Get information about the cluster
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

# ================================================================
# Start with optional MongoDB components
# ================================================================

- name: Get an existing MongoDB Secret
  when: mongodb_full.secret_ref is not defined
  k8s_facts:
    api_version: v1
    kind: Secret
    name: "{{name}}-mongodb-connection"
    namespace: '{{ ansible_operator_meta.namespace }}'
  register: mongodb_secret

- name: The MongoDB Secret is present
  when: mongodb_secret.resources is defined and mongodb_secret.resources|length == 0
  k8s:
    state: present
    force: False
    definition: "{{ lookup('template', 'mongodb-secret.yml') | from_yaml  }}"

- name: The MongoDB PVC is present
  when: mongodb_full.install|bool and mongodb_full.persistent|bool
  k8s:
    state: present
    force: False
    definition: "{{ lookup('template', 'mongodb-pvc.yml') | from_yaml  }}"

- name: The MongoDB Deployment is present if mongodb_full.install == true
  when: mongodb_full.install|bool
  k8s:
    state: "{{ 'present' if mongodb_full.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'mongodb-deployment.yml') | from_yaml  }}"

- name: The MongoDB Service is present if mongodb_full.install == true
  when: mongodb_full.install|bool
  k8s:
    state: "{{ 'present' if mongodb_full.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'mongodb-service.yml') | from_yaml  }}"

# ================================================================
# Next deal with Webapp components
# ================================================================

- name: The Webapp Deployment is present
  k8s:
    state: present
    definition: "{{ lookup('template', 'webapp-deployment.yml') | from_yaml  }}"

- name: The Webapp Service is present
  k8s:
    state: present
    definition: "{{ lookup('template', 'webapp-service.yml') | from_yaml  }}"

# ================================================================
# We have to determine routes before proceeding with configuration
# ================================================================

- name: The Webapp Route is present if OpenShift
  when: "'route.openshift.io' in api_groups"
  k8s:
    state: present
    definition: "{{ lookup('template', 'webapp-route.yml') | from_yaml  }}"
