# permissions for end users to edit fruitscataloggs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fruitscatalogg-editor-role
rules:
- apiGroups:
  - redhat.com
  resources:
  - fruitscataloggs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhat.com
  resources:
  - fruitscataloggs/status
  verbs:
  - get
