# permissions for end users to view fruitscataloggs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fruitscatalogg-viewer-role
rules:
- apiGroups:
  - redhat.com
  resources:
  - fruitscataloggs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhat.com
  resources:
  - fruitscataloggs/status
  verbs:
  - get
