# permissions for end users to edit fruitscataloga1s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fruitscataloga1-editor-role
rules:
- apiGroups:
  - redhat.com
  resources:
  - fruitscataloga1s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhat.com
  resources:
  - fruitscataloga1s/status
  verbs:
  - get
