# permissions for end users to view fruitscataloga1s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fruitscataloga1-viewer-role
rules:
- apiGroups:
  - redhat.com
  resources:
  - fruitscataloga1s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhat.com
  resources:
  - fruitscataloga1s/status
  verbs:
  - get
