kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: finalizer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: 
      - "*"
    resources:
      - pods/finalizers
      - deployments/finalizers
      - persistentvolumeclaims/finalizers
      - secrets/finalizers
      - services/finalizers
    verbs: 
      - "*"
  - apiGroups: 
      - ""
    resources:
      - pods/finalizers
      - deployments/finalizers
      - persistentvolumeclaims/finalizers
      - secrets/finalizers
      - services/finalizers
    verbs: 
      - "*"