kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{name}}-mongodb"
  namespace: '{{ ansible_operator_meta.namespace }}'
  labels:
    app: "{{name}}"
    container: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{mongodb.volume_size}}"