# permissions for end users to view fruitscatalogh1s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fruitscatalogh1-viewer-role
rules:
- apiGroups:
  - redhat.com
  resources:
  - fruitscatalogh1s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhat.com
  resources:
  - fruitscatalogh1s/status
  verbs:
  - get
