# permissions for end users to edit fruitscatalogg1s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fruitscatalogg1-editor-role
rules:
- apiGroups:
  - redhat.com
  resources:
  - fruitscatalogg1s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhat.com
  resources:
  - fruitscatalogg1s/status
  verbs:
  - get
