# permissions for end users to view fruitscatalogg1s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fruitscatalogg1-viewer-role
rules:
- apiGroups:
  - redhat.com
  resources:
  - fruitscatalogg1s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhat.com
  resources:
  - fruitscatalogg1s/status
  verbs:
  - get
