kind: Service
apiVersion: v1
metadata:
  name: "{{name}}-mongodb"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    container: mongodb
spec:
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: "{{name}}"
    container: mongodb
  type: ClusterIP
  sessionAffinity: None