apiVersion: v1
kind: Service
metadata:
  name: "{{name}}-webapp"
  labels:
    app: "{{name}}"
    container: webapp
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: "{{name}}"
    deploymentconfig: webapp
  type: ClusterIP
  sessionAffinity: None